import { MigrateUpArgs, MigrateDownArgs, sql } from "@payloadcms/db-vercel-postgres";

/**
 * Phase 6 of `plan/architecture-site-restructure-1.md`: the six remaining
 * CONCEPT §6 pages, in one migration.
 *
 * Generated by `payload migrate:create` and then hand-edited in exactly one way,
 * following the Phase 4 precedent recorded in that plan: **`IF EXISTS` was added
 * to every `DROP TABLE` / `DROP CONSTRAINT` / `DROP INDEX` / `DROP COLUMN`**, and
 * to the two `ALTER TABLE … DISABLE ROW LEVEL SECURITY` statements that target a
 * table this migration drops. The migration snapshot has been wrong about the
 * current schema before — a constraint it declared did not exist after a clean
 * replay, which aborted `migrate:fresh` — and a tolerant drop is the fix. Every
 * `CREATE` stays strict, so a genuine conflict still fails loudly.
 *
 * Audited for `RENAME`: there are none. `migrate:create` offered a rename for
 * most of the ~40 new localized columns (the two dropped `abertura_eyebrow`
 * columns and the dropped `o_que_trazem_eyebrow` made every addition look like a
 * possible rename of one of them); every question was answered "create".
 *
 * What it does, per page:
 *
 *   · **analise** — adds `aVisao.plate` (image · painter · workTitle · year),
 *     `oMetodo.closingLine`, `sonhoAmpliado.intro`, the three provenance fields on
 *     each `sonhoAmpliado.parallels` row, and `oQueTrazem.linkLabel`; drops
 *     `oQueTrazem.eyebrow` (DESIGN §6 bans the per-section kicker, so the field
 *     could never reach the page).
 *   · **orientacaoProfissional** — turns `nemCoaching.plate` from a bare upload
 *     into a plate group, so `pagePlateFrom` normalizes it and the frame can print
 *     a gallery label; adds `nemCoaching.anchor` for the vocation-as-individuação
 *     sentence.
 *   · **sobre** — adds the `abertura` tab (heading + lead); **drops the
 *     `credencial` tab and its two tables**, which duplicated
 *     `clinica.identity.credentials` (the same removal TASK-035 made on
 *     `page-inicio` in `20260805_031704`, for the same reason); adds
 *     `aClinica.linkLabel`.
 *   · **perguntas** — adds the plate group and the `fecho` tab; drops
 *     `abertura.eyebrow`.
 *   · **internacional** — adds the plate group on `brasileirosFora`, and
 *     **localizes `cities[].city`**, which previously printed "Nova York" inside an
 *     English sentence.
 *   · **privacidade** — adds the `responsavel` tab (heading · body · rights ·
 *     confidentiality) and `bilheteNota.linkLabel`; drops `abertura.eyebrow`; sets
 *     both list rows' `text` NOT NULL, because on that page a dropped half-row is
 *     a disclosure that silently vanished. Both tables are empty (Phase 4 seeded
 *     the page blank), so the constraint applies cleanly.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE IF EXISTS "page_sobre_credencial_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE IF EXISTS "page_sobre_credencial_items_locales" DISABLE ROW LEVEL SECURITY;
  DROP TABLE IF EXISTS "page_sobre_credencial_items" CASCADE;
  DROP TABLE IF EXISTS "page_sobre_credencial_items_locales" CASCADE;
  ALTER TABLE "page_orientacao_profissional" DROP CONSTRAINT IF EXISTS "page_orientacao_profissional_nem_coaching_plate_id_media_id_fk";
  
  DROP INDEX IF EXISTS "page_orientacao_profissional_nem_coaching_nem_coaching_p_idx";
  ALTER TABLE "page_privacidade_guarda_items_locales" ALTER COLUMN "text" SET NOT NULL;
  ALTER TABLE "page_privacidade_nunca_faz_items_locales" ALTER COLUMN "text" SET NOT NULL;
  ALTER TABLE "page_analise_sonho_ampliado_parallels" ADD COLUMN "painter" varchar;
  ALTER TABLE "page_analise_sonho_ampliado_parallels" ADD COLUMN "year" varchar;
  ALTER TABLE "page_analise_sonho_ampliado_parallels_locales" ADD COLUMN "work_title" varchar;
  ALTER TABLE "page_analise" ADD COLUMN "a_visao_plate_image_id" integer;
  ALTER TABLE "page_analise" ADD COLUMN "a_visao_plate_painter" varchar;
  ALTER TABLE "page_analise" ADD COLUMN "a_visao_plate_year" varchar;
  ALTER TABLE "page_analise_locales" ADD COLUMN "a_visao_plate_work_title" varchar;
  ALTER TABLE "page_analise_locales" ADD COLUMN "o_metodo_closing_line" varchar;
  ALTER TABLE "page_analise_locales" ADD COLUMN "o_que_trazem_link_label" varchar;
  ALTER TABLE "page_analise_locales" ADD COLUMN "sonho_ampliado_intro" varchar;
  ALTER TABLE "page_orientacao_profissional" ADD COLUMN "nem_coaching_plate_image_id" integer;
  ALTER TABLE "page_orientacao_profissional" ADD COLUMN "nem_coaching_plate_painter" varchar;
  ALTER TABLE "page_orientacao_profissional" ADD COLUMN "nem_coaching_plate_year" varchar;
  ALTER TABLE "page_orientacao_profissional_locales" ADD COLUMN "nem_coaching_anchor" varchar;
  ALTER TABLE "page_orientacao_profissional_locales" ADD COLUMN "nem_coaching_plate_work_title" varchar;
  ALTER TABLE "page_sobre_locales" ADD COLUMN "abertura_heading" varchar;
  ALTER TABLE "page_sobre_locales" ADD COLUMN "abertura_lead" jsonb;
  ALTER TABLE "page_sobre_locales" ADD COLUMN "a_clinica_link_label" varchar;
  ALTER TABLE "page_perguntas" ADD COLUMN "plate_image_id" integer;
  ALTER TABLE "page_perguntas" ADD COLUMN "plate_painter" varchar;
  ALTER TABLE "page_perguntas" ADD COLUMN "plate_year" varchar;
  ALTER TABLE "page_perguntas_locales" ADD COLUMN "plate_work_title" varchar;
  ALTER TABLE "page_perguntas_locales" ADD COLUMN "fecho_heading" varchar;
  ALTER TABLE "page_perguntas_locales" ADD COLUMN "fecho_body" varchar;
  ALTER TABLE "page_perguntas_locales" ADD COLUMN "fecho_whatsapp_label" varchar;
  ALTER TABLE "page_perguntas_locales" ADD COLUMN "fecho_link_label" varchar;
  ALTER TABLE "page_internacional_brasileiros_fora_cities_locales" ADD COLUMN "city" varchar NOT NULL;
  ALTER TABLE "page_internacional" ADD COLUMN "brasileiros_fora_plate_image_id" integer;
  ALTER TABLE "page_internacional" ADD COLUMN "brasileiros_fora_plate_painter" varchar;
  ALTER TABLE "page_internacional" ADD COLUMN "brasileiros_fora_plate_year" varchar;
  ALTER TABLE "page_internacional_locales" ADD COLUMN "brasileiros_fora_plate_work_title" varchar;
  ALTER TABLE "page_privacidade_locales" ADD COLUMN "bilhete_nota_link_label" varchar;
  ALTER TABLE "page_privacidade_locales" ADD COLUMN "responsavel_heading" varchar;
  ALTER TABLE "page_privacidade_locales" ADD COLUMN "responsavel_body" jsonb;
  ALTER TABLE "page_privacidade_locales" ADD COLUMN "responsavel_rights" varchar;
  ALTER TABLE "page_privacidade_locales" ADD COLUMN "responsavel_confidentiality" varchar;
  ALTER TABLE "clinica_locales" ADD COLUMN "notes_international" varchar;
  ALTER TABLE "page_analise" ADD CONSTRAINT "page_analise_a_visao_plate_image_id_media_id_fk" FOREIGN KEY ("a_visao_plate_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_orientacao_profissional" ADD CONSTRAINT "page_orientacao_profissional_nem_coaching_plate_image_id_media_id_fk" FOREIGN KEY ("nem_coaching_plate_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_perguntas" ADD CONSTRAINT "page_perguntas_plate_image_id_media_id_fk" FOREIGN KEY ("plate_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_internacional" ADD CONSTRAINT "page_internacional_brasileiros_fora_plate_image_id_media_id_fk" FOREIGN KEY ("brasileiros_fora_plate_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "page_analise_a_visao_plate_a_visao_plate_image_idx" ON "page_analise" USING btree ("a_visao_plate_image_id");
  CREATE INDEX "page_orientacao_profissional_nem_coaching_plate_nem_coac_idx" ON "page_orientacao_profissional" USING btree ("nem_coaching_plate_image_id");
  CREATE INDEX "page_perguntas_plate_plate_image_idx" ON "page_perguntas" USING btree ("plate_image_id");
  CREATE INDEX "page_internacional_brasileiros_fora_plate_brasileiros_fo_idx" ON "page_internacional" USING btree ("brasileiros_fora_plate_image_id");
  ALTER TABLE "page_analise_locales" DROP COLUMN IF EXISTS "o_que_trazem_eyebrow";
  ALTER TABLE "page_orientacao_profissional" DROP COLUMN IF EXISTS "nem_coaching_plate_id";
  ALTER TABLE "page_perguntas_locales" DROP COLUMN IF EXISTS "abertura_eyebrow";
  ALTER TABLE "page_internacional_brasileiros_fora_cities" DROP COLUMN IF EXISTS "city";
  ALTER TABLE "page_privacidade_locales" DROP COLUMN IF EXISTS "abertura_eyebrow";`);
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "page_sobre_credencial_items" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL
  );
  
  CREATE TABLE "page_sobre_credencial_items_locales" (
  	"text" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" varchar NOT NULL
  );
  
  ALTER TABLE "page_analise" DROP CONSTRAINT IF EXISTS "page_analise_a_visao_plate_image_id_media_id_fk";
  
  ALTER TABLE "page_orientacao_profissional" DROP CONSTRAINT IF EXISTS "page_orientacao_profissional_nem_coaching_plate_image_id_media_id_fk";
  
  ALTER TABLE "page_perguntas" DROP CONSTRAINT IF EXISTS "page_perguntas_plate_image_id_media_id_fk";
  
  ALTER TABLE "page_internacional" DROP CONSTRAINT IF EXISTS "page_internacional_brasileiros_fora_plate_image_id_media_id_fk";
  
  DROP INDEX IF EXISTS "page_analise_a_visao_plate_a_visao_plate_image_idx";
  DROP INDEX IF EXISTS "page_orientacao_profissional_nem_coaching_plate_nem_coac_idx";
  DROP INDEX IF EXISTS "page_perguntas_plate_plate_image_idx";
  DROP INDEX IF EXISTS "page_internacional_brasileiros_fora_plate_brasileiros_fo_idx";
  ALTER TABLE "page_privacidade_guarda_items_locales" ALTER COLUMN "text" DROP NOT NULL;
  ALTER TABLE "page_privacidade_nunca_faz_items_locales" ALTER COLUMN "text" DROP NOT NULL;
  ALTER TABLE "page_analise_locales" ADD COLUMN "o_que_trazem_eyebrow" varchar;
  ALTER TABLE "page_orientacao_profissional" ADD COLUMN "nem_coaching_plate_id" integer;
  ALTER TABLE "page_perguntas_locales" ADD COLUMN "abertura_eyebrow" varchar;
  ALTER TABLE "page_internacional_brasileiros_fora_cities" ADD COLUMN "city" varchar NOT NULL;
  ALTER TABLE "page_privacidade_locales" ADD COLUMN "abertura_eyebrow" varchar;
  ALTER TABLE "page_sobre_credencial_items" ADD CONSTRAINT "page_sobre_credencial_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."page_sobre"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "page_sobre_credencial_items_locales" ADD CONSTRAINT "page_sobre_credencial_items_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."page_sobre_credencial_items"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "page_sobre_credencial_items_order_idx" ON "page_sobre_credencial_items" USING btree ("_order");
  CREATE INDEX "page_sobre_credencial_items_parent_id_idx" ON "page_sobre_credencial_items" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "page_sobre_credencial_items_locales_locale_parent_id_unique" ON "page_sobre_credencial_items_locales" USING btree ("_locale","_parent_id");
  ALTER TABLE "page_orientacao_profissional" ADD CONSTRAINT "page_orientacao_profissional_nem_coaching_plate_id_media_id_fk" FOREIGN KEY ("nem_coaching_plate_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "page_orientacao_profissional_nem_coaching_nem_coaching_p_idx" ON "page_orientacao_profissional" USING btree ("nem_coaching_plate_id");
  ALTER TABLE "page_analise_sonho_ampliado_parallels" DROP COLUMN IF EXISTS "painter";
  ALTER TABLE "page_analise_sonho_ampliado_parallels" DROP COLUMN IF EXISTS "year";
  ALTER TABLE "page_analise_sonho_ampliado_parallels_locales" DROP COLUMN IF EXISTS "work_title";
  ALTER TABLE "page_analise" DROP COLUMN IF EXISTS "a_visao_plate_image_id";
  ALTER TABLE "page_analise" DROP COLUMN IF EXISTS "a_visao_plate_painter";
  ALTER TABLE "page_analise" DROP COLUMN IF EXISTS "a_visao_plate_year";
  ALTER TABLE "page_analise_locales" DROP COLUMN IF EXISTS "a_visao_plate_work_title";
  ALTER TABLE "page_analise_locales" DROP COLUMN IF EXISTS "o_metodo_closing_line";
  ALTER TABLE "page_analise_locales" DROP COLUMN IF EXISTS "o_que_trazem_link_label";
  ALTER TABLE "page_analise_locales" DROP COLUMN IF EXISTS "sonho_ampliado_intro";
  ALTER TABLE "page_orientacao_profissional" DROP COLUMN IF EXISTS "nem_coaching_plate_image_id";
  ALTER TABLE "page_orientacao_profissional" DROP COLUMN IF EXISTS "nem_coaching_plate_painter";
  ALTER TABLE "page_orientacao_profissional" DROP COLUMN IF EXISTS "nem_coaching_plate_year";
  ALTER TABLE "page_orientacao_profissional_locales" DROP COLUMN IF EXISTS "nem_coaching_anchor";
  ALTER TABLE "page_orientacao_profissional_locales" DROP COLUMN IF EXISTS "nem_coaching_plate_work_title";
  ALTER TABLE "page_sobre_locales" DROP COLUMN IF EXISTS "abertura_heading";
  ALTER TABLE "page_sobre_locales" DROP COLUMN IF EXISTS "abertura_lead";
  ALTER TABLE "page_sobre_locales" DROP COLUMN IF EXISTS "a_clinica_link_label";
  ALTER TABLE "page_perguntas" DROP COLUMN IF EXISTS "plate_image_id";
  ALTER TABLE "page_perguntas" DROP COLUMN IF EXISTS "plate_painter";
  ALTER TABLE "page_perguntas" DROP COLUMN IF EXISTS "plate_year";
  ALTER TABLE "page_perguntas_locales" DROP COLUMN IF EXISTS "plate_work_title";
  ALTER TABLE "page_perguntas_locales" DROP COLUMN IF EXISTS "fecho_heading";
  ALTER TABLE "page_perguntas_locales" DROP COLUMN IF EXISTS "fecho_body";
  ALTER TABLE "page_perguntas_locales" DROP COLUMN IF EXISTS "fecho_whatsapp_label";
  ALTER TABLE "page_perguntas_locales" DROP COLUMN IF EXISTS "fecho_link_label";
  ALTER TABLE "page_internacional_brasileiros_fora_cities_locales" DROP COLUMN IF EXISTS "city";
  ALTER TABLE "page_internacional" DROP COLUMN IF EXISTS "brasileiros_fora_plate_image_id";
  ALTER TABLE "page_internacional" DROP COLUMN IF EXISTS "brasileiros_fora_plate_painter";
  ALTER TABLE "page_internacional" DROP COLUMN IF EXISTS "brasileiros_fora_plate_year";
  ALTER TABLE "page_internacional_locales" DROP COLUMN IF EXISTS "brasileiros_fora_plate_work_title";
  ALTER TABLE "page_privacidade_locales" DROP COLUMN IF EXISTS "bilhete_nota_link_label";
  ALTER TABLE "page_privacidade_locales" DROP COLUMN IF EXISTS "responsavel_heading";
  ALTER TABLE "page_privacidade_locales" DROP COLUMN IF EXISTS "responsavel_body";
  ALTER TABLE "page_privacidade_locales" DROP COLUMN IF EXISTS "responsavel_rights";
  ALTER TABLE "page_privacidade_locales" DROP COLUMN IF EXISTS "responsavel_confidentiality";
  ALTER TABLE "clinica_locales" DROP COLUMN IF EXISTS "notes_international";`);
}
